development:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  database: db/development.sqlite3

test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  database: db/test.sqlite3

production:
  database: kutu_production
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 1000
